name: Changelog

on:
    pull_request:
    push:
        branches:
            - main

permissions:
    contents: read

jobs:
    changelog:
        name: Generate changelog
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install git-cliff
              uses: taiki-e/install-action@git-cliff

            - name: Generate changelog
              run: git-cliff -o CHANGELOG.md

            - name: Check changelog diff
              run: git diff --exit-code CHANGELOG.md
